# https://commitizen-tools.github.io/commitizen/bump/#configuration

[tool.commitizen]
gpg_sign = true
major_version_zero = true
name = "cz_conventional_commits"
post_bump_hooks = [
  "make .release-post-bump",
]
pre_bump_hooks = [
  "make build",
]
tag_format = "v$version"
update_changelog_on_bump = true
version = "0.2.1"
version_files = [
  "docs/conf.py:version = release",
  "pyproject.toml:version =",
  "python/logseq_doctor/__init__.py",
  "README.rst:github",
  "rust/logseq-doctor/Cargo.toml:version =",
  "rust/logseq/Cargo.toml:version =",
]
